export const BOOKDATA = [
  {
    key: "1",
    title: "Man's search for meaning",
    isbn: 9788971460108,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Philosophy",
  },
  {
    key: "2",
    title: "Wings of Fire: An Autobiography 1st Edition",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154195,
    price: 4,
    availableItems: 8,
    Subject: "Autobiography",
  },
  {
    key: "3",
    title: "A Century is not Enough: My Roller-coaster Ride to Success",
    author: "Sourav Ganguly",
    isbn: 9789386228567,
    price: 4,
    availableItems: 6,
    Subject: "Autobiography",
  },
  {
    key: "4",
    title: "The Another World",
    author: "JAMES JONES",
    isbn: 9780385333641,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "5",
    title: "React Design Patterns and Best Practices",
    author: "Richard Dawkins",
    isbn: 9780593061732,
    price: 2,
    availableItems: 1,
    Subject: "Programming",
  },
  {
    key: "6",
    title: "The Seven Wonders",
    isbn: 9788971460118,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Philosophy",
  },
  {
    key: "7",
    title: "Ignited Minds",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154295,
    price: 4,
    availableItems: 8,
    Subject: "Philosophy",
  },
  {
    key: "8",
    title: "Playing It My Way",
    author: "Sachin Tendulkar",
    isbn: 9781473612569,
    price: 4,
    availableItems: 6,
    Subject: "Autobiography",
  },
  {
    key: "9",
    title: "From Here to Eternity",
    author: "JAMES JONES",
    isbn: 9780385333691,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "10",
    title: "The Greatest Show on Earth: The Evidence for Evolution",
    author: "Richard Dawkins",
    isbn: 9780593061733,
    price: 2,
    availableItems: 1,
    Subject: "Science",
  },
  {
    key: "11",
    title: "PUMPS FOR CHEMICAL PROCESSING",
    isbn: 9587771460108,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Engineering",
  },
  {
    key: "12",
    title: "India 2020",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154225,
    price: 4,
    availableItems: 8,
    Subject: "Vision",
  },
  {
    key: "13",
    title: "My Last Test Match",
    author: "Sachin Tendulkar",
    isbn: 9781263612630,
    price: 4,
    availableItems: 6,
    Subject: "Sports",
  },
  {
    key: "14",
    title: "NEURAL NETWORK MODELS - THEORY AND PROJECTS",
    author: "JAMES JONES",
    isbn: 9780385444741,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "15",
    title: "ADAPTIVE INTERNAL MODEL CONTROL",
    author: "Datta Aniruddha",
    isbn: 3540762523,
    price: 2,
    availableItems: 1,
    Subject: "Engineering",
  },
  {
    key: "1",
    title: "Man's search for meaning",
    isbn: 9788971460108,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Philosophy",
  },
  {
    key: "2",
    title: "Wings of Fire: An Autobiography 1st Edition",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154195,
    price: 4,
    availableItems: 8,
    Subject: "Autobiography",
  },
  {
    key: "3",
    title: "A Century is not Enough: My Roller-coaster Ride to Success",
    author: "Sourav Ganguly",
    isbn: 9789386228567,
    price: 4,
    availableItems: 6,
    Subject: "Autobiography",
  },
  {
    key: "4",
    title: "The Another World",
    author: "JAMES JONES",
    isbn: 9780385333641,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "5",
    title: "React Design Patterns and Best Practices",
    author: "Richard Dawkins",
    isbn: 9780593061732,
    price: 2,
    availableItems: 1,
    Subject: "Programming",
  },
  {
    key: "6",
    title: "The Seven Wonders",
    isbn: 9788971460118,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Philosophy",
  },
  {
    key: "7",
    title: "Ignited Minds",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154295,
    price: 4,
    availableItems: 8,
    Subject: "Philosophy",
  },
  {
    key: "8",
    title: "Playing It My Way",
    author: "Sachin Tendulkar",
    isbn: 9781473612569,
    price: 4,
    availableItems: 6,
    Subject: "Autobiography",
  },
  {
    key: "9",
    title: "From Here to Eternity",
    author: "JAMES JONES",
    isbn: 9780385333691,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "10",
    title: "The Greatest Show on Earth: The Evidence for Evolution",
    author: "Richard Dawkins",
    isbn: 9780593061733,
    price: 2,
    availableItems: 1,
    Subject: "Science",
  },
  {
    key: "11",
    title: "PUMPS FOR CHEMICAL PROCESSING",
    isbn: 9587771460108,
    author: "Viktor Frankl",
    price: 5,
    availableItems: 7,
    Subject: "Engineering",
  },
  {
    key: "12",
    title: "India 2020",
    author: "Dr.A. P. J. Abdul Kalam",
    isbn: 9788173154225,
    price: 4,
    availableItems: 8,
    Subject: "Vision",
  },
  {
    key: "13",
    title: "My Last Test Match",
    author: "Sachin Tendulkar",
    isbn: 9781263612630,
    price: 4,
    availableItems: 6,
    Subject: "Sports",
  },
  {
    key: "14",
    title: "NEURAL NETWORK MODELS - THEORY AND PROJECTS",
    author: "JAMES JONES",
    isbn: 9780385444741,
    price: 4,
    availableItems: 2,
    Subject: "Historical Fiction",
  },
  {
    key: "15",
    title: "ADAPTIVE INTERNAL MODEL CONTROL",
    author: "Datta Aniruddha",
    isbn: 3540762523,
    price: 2,
    availableItems: 1,
    Subject: "Engineering",
  },
];
